### ISSUE TITLE
Bower file is missing dependency on Angular

### ISSUE THREAD

**Issue by tlvenn** [driftyco/ionic-service-core#16]
Hi,

All ionic services currently depend on Angular and yet dont define it as dependency in  bower. Is there any reason for that ?

**Comment by ericb** [comment]
We are planning to move away from bower, but we haven't marked angular as a dependency as the real dependency is on the ionicframework (which already has the dependency on angular)

**Comment by tlvenn** [comment]
I dont really know which package management you will use but for example Jspm (used by Angular 2) does not allow you to leverage transitive dependency. If your code depends on C and B, just because B depends on C, you cant only list B as the sole dependency. In order to import C and use it in your code, you will have to declare it as dependency.

Anyway I am digressing a bit.
