### ISSUE TITLE
$ionicAppProvider.identify() yields SyntaxError: Unexpected token o in ionic-core.js:162:29

### ISSUE THREAD

**Issue by jtammen** [driftyco/ionic-service-core#2]
Hi,

I try to connect my app to ionic.io by adding the `ionic-service-core` module via `ionic add ionic-service-core\#master` and adding this to my app's code:

``` javascript
.config([ '$ionicAppProvider', function($ionicAppProvider) {
  $ionicAppProvider.identify({
    app_id : 'MY_ADD_ID',
    api_key : 'MY_API_KEY'
  });
} ])
```

Unfortunately, this fails because in [this line](https://github.com/driftyco/ionic-service-core/blob/master/ionic-core.js#L162), the response data already seems to be parsed and so the `JSON.parse()` call fails.

Output of `ionic info`:

```
OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.20
Xcode version: Xcode 6.3 Build version 6D570
ios-sim version: 3.0.0
ios-deploy version: Not installed
```

Thanks,
Jan.

**Comment by mlynch** [comment]
cc @Fuiste

**Comment by Fuiste** [comment]
I see what the problem was.  I've removed the offending net call, as it should no longer be necessary.

**Comment by jtammen** [comment]
Thanks (-:
