### ISSUE TITLE
bug: $ionicUser.identify problem. 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-service-core#20]
_From @tigrus on July 21, 2015 10:55_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Doing: 

```
    $ionicUser.identify({ 
        'user_id':$ionicUser.generateUUID(); 
    })
```

Getting 403 error: 

```
   {"detail":"CSRF Failed: CSRF token missing or incorrect."}
```

After setting CSRF from cookies to header X-CSRFToken getting 405 error:

``````
   {"detail":"Method \"POST\" not allowed."}
```</span>

<span is-issue-template></span>


_Copied from original issue: driftyco/ionic#4117_
``````

**Comment by ericb** [comment]
@tigrus Are you still experiencing this issue?

**Comment by tigrus** [comment]
@ericb I've migrated to pushwoosh.
