### ISSUE TITLE
0.1.9 TAG hardcodes app_id 9977a467 in $ionicCoreSettings

### ISSUE THREAD

**Issue by djett41** [driftyco/ionic-service-core#22]
It seems that the 0.1.9 tag isn't consistent with the ionic-core.js although they were updated the same day.

In $ionicCoreSettings for the tag 0.1.9, theres a hardoded app_id and public key, and since this app_id, api_key is checked before ionicApp, everyones events will get forwarded to this app_id rather than their own..

May need to do another bower patch to fix this issue since bower pulls from the GIT tags.

**Comment by ericb** [comment]
@djett41 I thought we had patched this up already, thanks for pointing it out. I'll get that patched in today. Cheers! :beers:

**Comment by ericb** [comment]
Updated to 0.1.10.

**Comment by djett41** [comment]
No prob my man!! thanks
