### ISSUE TITLE
firebase authWithPassword callback is not firing when ionic-service-core is included

### ISSUE THREAD

**Issue by crascher** [driftyco/ionic-service-core#24]
The problem occurs on my Android 4.4 device. In the browser it is working fine. The response of the request can be viewed in the chrome dev tools network tab, but the callback is not firing.

<code>
 FirebaseAuth.$authWithPassword(user).then(function(authData) {
                console.log(authData);
            }).catch(function(error) {
                console.log(error);
            });
</code>

I am using 
"ionic": "driftyco/ionic-bower#1.0.1",
"ionic-service-core": "0.1.10",
"firebase": "2.2.9",
"angularfire": "1.1.2"

**Comment by ericb** [comment]
There is no connection between firebase and ionic-service-core. I'd suggest checking out the [firebase help page](https://www.firebase.com/docs/help/)
