### ISSUE TITLE
Could not satisfy the request's Accept header

### ISSUE THREAD

**Issue by RangerRick** [driftyco/ionic-service-core#8]
I have an Ionic app which consumes a large number of XML ReST requests using Basic Authorization.

If you override Angular's default HTTP service to use an alternate default 'Accept' header, $ionicUser.identify() fails with the following response:

``` json
{
    "config": {
        "data": {
            "_id": "XXXX",
            "device": {
                "screen_height": 1334,
                "screen_width": 750
            },
            "is_on_device": true,
            "user_id": "XXXX"
        },
        "headers": {
            "Accept": "application/xml",
            "Authorization": "Basic YYYY",
            "Content-Type": "application/json;charset=utf-8"
        },
        "method": "POST",
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "url": "https://apps.ionic.io/api/v1/app/XXXX/users/identify"
    },
    "data": {
        "detail": "Could not satisfy the request's Accept header"
    },
    "status": 406,
    "statusText": "NOT ACCEPTABLE"
}
```

$ionicUser (and potentially other apps.ionic.io tools) should probably explicitly ask for the Accepts: header it expects when making API calls.

As a workaround, I have changed my code to not override the default Accept: header and instead set it per-request, for now.

**Comment by ericb** [comment]
I will change this on our end, but in the meantime, you can have both accepted by passing both xml and json content types into the Accepts header.

```
$http.defaults.headers.common.Accept = 'application/xml, application/json';
```
